src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="creator")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=Payment::class, mappedBy="user")
     */
    private $payments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $paypalme_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $paypal_clientid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;

    /**
     * @ORM\Column(type="integer")
     */
    private $streetnumber;

    /**
     * @ORM\Column(type="integer")
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $APIToken;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->payments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setCreator($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getCreator() === $this) {
                $order->setCreator(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Payment[]
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(Payment $payment): self
    {
        if (!$this->payments->contains($payment)) {
            $this->payments[] = $payment;
            $payment->setUser($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): self
    {
        if ($this->payments->removeElement($payment)) {
            // set the owning side to null (unless already changed)
            if ($payment->getUser() === $this) {
                $payment->setUser(null);
            }
        }

        return $this;
    }

    public function totalPayments(): float{
        $sum = 0.0;
        foreach ($this->getPayments() as $payment){
            $sum = $sum + $payment->getAmount();
        }
        return $sum;
    }

    public function pendingPayments(): int{
        $count = 0;
        foreach ($this->getPayments() as $payment){
            if($payment->getFulfillmentDate() == null){
                $count++;
            }
        }
        return $count;
    }

    public function pendingPostage(): int{
        $count = 0;
        foreach ($this->getOrders() as $order){
            if(sizeof($order->getDHLLabels()) == 0){
                $count++;
            }
        }
        return $count;
    }

    public function getPaypalmeName(): ?string
    {
        return $this->paypalme_name;
    }

    public function setPaypalmeName(?string $paypalme_name): self
    {
        $this->paypalme_name = $paypalme_name;

        return $this;
    }

    public function getPaypalClientid(): ?string
    {
        return $this->paypal_clientid;
    }

    public function setPaypalClientid(?string $paypal_clientid): self
    {
        $this->paypal_clientid = $paypal_clientid;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getStreetnumber(): ?int
    {
        return $this->streetnumber;
    }

    public function setStreetnumber(int $streetnumber): self
    {
        $this->streetnumber = $streetnumber;

        return $this;
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(int $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAPIToken(): ?string
    {
        return $this->APIToken;
    }

    public function setAPIToken(?string $APIToken): self
    {
        $this->APIToken = $APIToken;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

templates/content/me.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h3 class="card-title">Mein Profil</h3>
                </div>
                {{ form_start(form) }}
                <div class="card-body">
                    Einer der beiden Werte MUSS angegeben sein, damit das Zahlungssystem funktioniert. Ansonsten wird lediglich die Adresseingabe durchgeführt.
                    <br><br>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label class="bmd-label-floating">Vorname <span class="text-danger">*</span></label>
                            {{ form_widget(form.firstname, {attr: {class: 'form-control'}, required: true}) }}
                        </div>
                        <div class="form-group col-md-6">
                            <label class="bmd-label-floating">Nachname <span class="text-danger">*</span></label>
                            {{ form_widget(form.lastname, {attr: {class: 'form-control'}, required: true}) }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label class="bmd-label-floating">eMail-Adresse <span class="text-danger">*</span></label>
                            {{ form_widget(form.email, {attr: {class: 'form-control'}, required: true}) }}
                        </div>
                        <div class="form-group col-md-6">
                            <label class="bmd-label-floating">Telefonnummer <small class="text-muted">Optional</small></label>
                            {{ form_widget(form.phone, {attr: {class: 'form-control'}, required: false}) }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label class="bmd-label-floating">PayPal API-ClientID <small class="text-muted">Optional</small></label>
                            {{ form_widget(form.paypal_clientid, {attr: {class: 'form-control'}, required: false}) }}
                        </div>
                    </div>
                </div>
                <div class="card-footer border-top">
                    <button type="submit" class="btn btn-success btn-block">Sichern</button>
                </div>
                {{ form_end(form) }}
            </div>
            <div class="card">
                <div class="card-header card-header-primary">
                    <h3 class="card-title">API-Zugang</h3>
                </div>
                <div class="card-body">
                    {{ app.user.aPIToken }}
                    <hr>
                    <a href="{{ path('app_security_generatetoken') }}" class="btn btn-warning">Neues Token generieren</a>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h3 class="card-title">Meine Adresse</h3>
                </div>
                {{ form_start(addressForm) }}
                <div class="card-body">
                    <div class="form-row">
                        <div class="form-group col-md-9">
                            <label class="bmd-label-floating">Straße <span class="text-danger">*</span></label>
                            {{ form_widget(addressForm.street, {attr: {class: 'form-control'}, required: true}) }}
                        </div>
                        <div class="form-group col-md-3">
                            <label class="bmd-label-floating">Hausnummer <span class="text-danger">*</span></label>
                            {{ form_widget(addressForm.streetnumber, {attr: {class: 'form-control'}, required: true}) }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label class="bmd-label-floating">Postleitzahl <span class="text-danger">*</span></label>
                            {{ form_widget(addressForm.zipcode, {attr: {class: 'form-control'}, required: true}) }}
                        </div>
                        <div class="form-group col-md-9">
                            <label class="bmd-label-floating">Stadt <span class="text-danger">*</span></label>
                            {{ form_widget(addressForm.city, {attr: {class: 'form-control'}, required: true}) }}
                        </div>
                    </div>
                </div>
                <div class="card-footer border-top">
                    <button type="submit" class="btn btn-success btn-block">Sichern</button>
                </div>
                {{ form_end(addressForm) }}
            </div>
        </div>
    </div>
{% endblock %}