src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $recipient_name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $recipient_zip;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $recipient_city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $recipient_street;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $recipient_streetNumber;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $creator;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_datetime;

    /**
     * @ORM\OneToMany(targetEntity=DHLLabel::class, mappedBy="ProductOrder")
     */
    private $dHLLabels;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $vinted_item_id;

    /**
     * @ORM\OneToOne(targetEntity=Payment::class, inversedBy="productOrder", cascade={"persist", "remove"})
     */
    private $payment;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $porto_price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $dhlpakid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $customerToken;

    public function __construct()
    {
        $this->dHLLabels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getRecipientName(): ?string
    {
        return $this->recipient_name;
    }

    public function setRecipientName(?string $recipient_name): self
    {
        $this->recipient_name = $recipient_name;

        return $this;
    }

    public function getRecipientZip(): ?int
    {
        return $this->recipient_zip;
    }

    public function setRecipientZip(?int $recipient_zip): self
    {
        $this->recipient_zip = $recipient_zip;

        return $this;
    }

    public function getRecipientCity(): ?string
    {
        return $this->recipient_city;
    }

    public function setRecipientCity(?string $recipient_city): self
    {
        $this->recipient_city = $recipient_city;

        return $this;
    }

    public function getRecipientStreet(): ?string
    {
        return $this->recipient_street;
    }

    public function setRecipientStreet(string $recipient_street): self
    {
        $this->recipient_street = $recipient_street;

        return $this;
    }

    public function getRecipientStreetNumber(): ?int
    {
        return $this->recipient_streetNumber;
    }

    public function setRecipientStreetNumber(?int $recipient_streetNumber): self
    {
        $this->recipient_streetNumber = $recipient_streetNumber;

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getCreationDatetime(): ?\DateTimeInterface
    {
        return $this->creation_datetime;
    }

    public function setCreationDatetime(\DateTimeInterface $creation_datetime): self
    {
        $this->creation_datetime = $creation_datetime;

        return $this;
    }

    /**
     * @return Collection|DHLLabel[]
     */
    public function getDHLLabels(): Collection
    {
        return $this->dHLLabels;
    }

    public function addDHLLabel(DHLLabel $dHLLabel): self
    {
        if (!$this->dHLLabels->contains($dHLLabel)) {
            $this->dHLLabels[] = $dHLLabel;
            $dHLLabel->setProductOrder($this);
        }

        return $this;
    }

    public function removeDHLLabel(DHLLabel $dHLLabel): self
    {
        if ($this->dHLLabels->removeElement($dHLLabel)) {
            // set the owning side to null (unless already changed)
            if ($dHLLabel->getProductOrder() === $this) {
                $dHLLabel->setProductOrder(null);
            }
        }

        return $this;
    }

    public function getVintedItemId(): ?string
    {
        return $this->vinted_item_id;
    }

    public function setVintedItemId(string $vinted_item_id): self
    {
        $this->vinted_item_id = $vinted_item_id;

        return $this;
    }

    public function getPayment(): ?Payment
    {
        return $this->payment;
    }

    public function setPayment(?Payment $payment): self
    {
        $this->payment = $payment;

        return $this;
    }

    public function getPortoPrice(): ?string
    {
        return $this->porto_price;
    }

    public function setPortoPrice(?string $porto_price): self
    {
        $this->porto_price = $porto_price;

        return $this;
    }

    public function getDhlpakid(): ?string
    {
        return $this->dhlpakid;
    }

    public function setDhlpakid(?string $dhlpakid): self
    {
        $this->dhlpakid = $dhlpakid;

        return $this;
    }

    public function getCustomerToken(): ?string
    {
        return $this->customerToken;
    }

    public function setCustomerToken(string $customerToken): self
    {
        $this->customerToken = $customerToken;

        return $this;
    }
}

src/Entity/Payment.php
<?php

namespace App\Entity;

use App\Repository\PaymentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PaymentRepository::class)
 */
class Payment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $amount;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="payments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fulfillment_date;

    /**
     * @ORM\OneToOne(targetEntity=Order::class, mappedBy="payment", cascade={"persist", "remove"})
     */
    private $productOrder;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getFulfillmentDate(): ?\DateTimeInterface
    {
        return $this->fulfillment_date;
    }

    public function setFulfillmentDate(?\DateTimeInterface $fulfillment_date): self
    {
        $this->fulfillment_date = $fulfillment_date;

        return $this;
    }

    public function getProductOrder(): ?Order
    {
        return $this->productOrder;
    }

    public function setProductOrder(?Order $productOrder): self
    {
        // unset the owning side of the relation if necessary
        if ($productOrder === null && $this->productOrder !== null) {
            $this->productOrder->setPayment(null);
        }

        // set the owning side of the relation if necessary
        if ($productOrder !== null && $productOrder->getPayment() !== $this) {
            $productOrder->setPayment($this);
        }

        $this->productOrder = $productOrder;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

templates/content/orders/details.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-md-12 col-lg-6">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h3 class="card-title">{{ order.name|raw }}</h3>
                </div>
                <div class="card-body">
                    <p><strong>Preis:</strong> {{ order.price|format_currency('EUR', locale='de') }}</p>
                    <p><strong>Versandkosten:</strong> {{ order.portoPrice|format_currency('EUR', locale='de') }}</p>
                    {% if order.payment %}
                        <p><strong>Bezahlung:</strong> <span class="text-success">{{ order.payment.amount|format_currency('EUR', locale='de') }} Euro Bezahlt via {{ order.payment.type }} am {{ order.payment.fulfillmentDate.format('d.m.Y') }}</span></p>
                    {% else %}
                        <p><strong>Bezahlung:</strong> <span class="text-danger">Noch nicht erfolgt!</span></p>
                    {% endif %}
                    {% if order.recipientName %}
                        <br>
                        <p><strong>Versandinformationen:</strong></p>
                        <p>{{ order.recipientName }}</p>
                        <p>{{ order.recipientStreet }} {{ order.recipientStreetNumber }}</p>
                        <p>{{ order.recipientZip }} {{ order.recipientCity }}</p>
                    {% endif %}
                    <div class="form-group">
                        <label for="customerToken">Kunden-URL</label>
                        <div class="input-group">
                            <input id="customerToken" class="form-control" type="text" disabled value="{{ app.request.getSchemeAndHttpHost() }}{{ path('app_customer_customer_addressform', {token: order.customerToken}) }}">
                            <div class="input-group-append">
                                <button class="input-group-btn btn btn-just-icon btn-sm" onclick="navigator.clipboard.writeText(document.getElementById('customerToken').value);$.notify({message: 'Der Link wurde in die Zwischenablage kopiert!'},{type: 'success', timer: 4000, placement: {from: 'top', align: 'right'}});"><i class="material-icons">content_copy</i></button>
                            </div>
                        </div>
                    </div>
                    {% if order.vintedItemId %}
                        <p><i>Importiert von Vinted</i></p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-12 col-lg-6">
            <div class="card">
                <div class="card-header card-header-warning">
                    <h3 class="card-title">Aktionen</h3>
                </div>
                <div class="card-body">
                    {% if order.payment == null%}
                        <button class="btn btn-lg btn-success" onclick="window.location.href = '{{ path('app_order_payment_manual', {id: order.id}) }}'">Manuelle Bezahlung</button>
                    {% endif %}
                    <button class="btn btn-lg btn-warning" onclick="window.location.href = '{{ path('app_order_setpost', {id: order.id}) }}'">Portokosten setzen</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        let orderID = '{{ order.id }}';

    </script>
{% endblock %}

templates/content/orders/list.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header card-header-tabs card-header-rose">
                    <div class="nav-tabs-navigation">
                        <div class="nav-tabs-wrapper">
                            <span class="nav-tabs-title">Orders:</span>
                            <ul class="nav nav-tabs" data-tabs="tabs">
                                <li class="nav-item">
                                    <a class="nav-link active" href="#active" data-toggle="tab">
                                        <i class="material-icons">bug_report</i> Alle
                                        <div class="ripple-container"></div>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#archived" data-toggle="tab">
                                        <i class="material-icons">code</i> Sendung ausstehend
                                        <div class="ripple-container"></div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card-body table-responsive">
                    <div class="tab-content">
                        <div class="tab-pane active show" id="active">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>Titel</th>
                                    <th>Betrag</th>
                                    <th>Erstellt</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for order in orders %}
                                        <tr>
                                            <td>{{ order.name|raw }}</td>
                                            <td>{{ order.price }}</td>
                                            <td>{{ order.creationDatetime.format('d.m.Y') }}</td>
                                            <td class="td-actions text-right float-right">
                                                <button type="button" rel="tooltip" title="Anzeigen" class="btn btn-primary btn-link btn-sm" onclick="window.location.href = '{{ path('app_order_order', {id: order.id}) }}'">
                                                    <i class="material-icons">edit</i>
                                                </button>
                                                <button type="button" rel="tooltip" title="Löschen" class="btn btn-danger btn-link btn-sm" onclick="window.location.href = '{{ path('app_order_delete', {id: order.id}) }}'" >
                                                    <i class="material-icons">close</i>
                                                </button>
                                            </td>
                                        </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        <div class="tab-pane" id="archived">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>Titel</th>
                                    <th>Betrag</th>
                                    <th>Erstellt</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for order in orders %}
                                    {% if order.dHLLabels.count == 0 %}
                                        <tr>
                                            <td>{{ order.name|raw }}</td>
                                            <td>{{ order.price }}</td>
                                            <td>{{ order.creationDatetime.format('d.m.Y') }}</td>
                                            <td class="td-actions text-right float-right">
                                                <button type="button" rel="tooltip" title="Anzeigen" class="btn btn-primary btn-link btn-sm" onclick="window.location.href = '{{ path('app_order_order', {id: order.id}) }}'">
                                                    <i class="material-icons">edit</i>
                                                </button>
                                                <button type="button" rel="tooltip" title="Löschen" class="btn btn-danger btn-link btn-sm" disabled>
                                                    <i class="material-icons">close</i>
                                                </button>
                                            </td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/content/orders/manuallyPaid.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header card-header-success">
                    <h3 class="card-title">Manuelle Bezahlung</h3>
                </div>
                <div class="card-body">
                    {{ form_start(form) }}
                    <div class="form-group">
                        <label class="bmd-label-floating">Betrag in Euro</label>
                        {{ form_widget(form.amount, {attr: {class: 'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        <label class="bmd-label-floating">Zahlungsmittel</label>
                        {{ form_widget(form.type, {attr: {class: 'form-control'}}) }}
                    </div>

                    <button type="submit" class="btn btn-success">Sichern</button>
                    {{ form_widget(form._token) }}
                    {{ form_end(form, {'render_rest' : false}) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        let orderID = '{{ order.id }}';

    </script>
{% endblock %}

templates/content/orders/setPostage.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header-success">
                    <h3 class="card-title">Versandkosten für {{ order.name }} setzen</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <div class="form-check form-check-radio form-check-inline">
                                    <label class="form-check-label">
                                        <input data-amount="0.00" class="form-check-input" type="radio" name="pack_type" id="inlineRadio1" value="custom" onchange="updateSelection()" checked>
                                        Eigene Versandkosten
                                        <span class="circle">
                                            <span class="check"></span>
                                        </span>
                                    </label>
                                </div>
                                {% for product in products %}
                                    <div class="form-check form-check-radio form-check-inline">
                                        <label class="form-check-label">
                                            <input class="form-check-input" data-amount="{{ product.amount }}" type="radio" name="pack_type" id="inlineRadio1" onchange="updateSelection()" value="{{ product.id }}">
                                            {{ product.displayName }} {{ product.maxWeight/1000 }} kg | {{ product.maxLength }}x{{ product.maxWidth }}x{{ product.maxDepth }}cm
                                            <span class="circle">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-md-6">
                                <div class="form-group ">
                                    <label for="postCost">Versandkosten</label>
                                    <input type="text" class="form-control" name="postCost" id="postCost" placeholder="Betrag in Euro" value="0,00">
                                </div>
                                <input type="submit" class="btn btn-primary btn-block" value="Sichern" name="submitted">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.getElementById('postCost').value = 0.00;

        function updateSelection(){
            let ele = document.getElementsByName('pack_type');

            var value = "";
            var amount = "";
            for(i = 0; i < ele.length; i++) {
                if(ele[i].checked){
                    value = ele[i].value
                    document.getElementById('postCost').value = ele[i].dataset.amount;
                }
            }


            if(value === 'custom'){
                document.getElementById('postCost').readonly = "READONLY";
            }else{
                document.getElementById('postCost').readonly = null;
            }
        }
    </script>
{% endblock %}