src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $recipient_name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $recipient_zip;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $recipient_city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $recipient_street;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $recipient_streetNumber;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $creator;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_datetime;

    /**
     * @ORM\OneToMany(targetEntity=DHLLabel::class, mappedBy="ProductOrder")
     */
    private $dHLLabels;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $vinted_item_id;

    /**
     * @ORM\OneToOne(targetEntity=Payment::class, inversedBy="productOrder", cascade={"persist", "remove"})
     */
    private $payment;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $porto_price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $dhlpakid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $customerToken;

    public function __construct()
    {
        $this->dHLLabels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getRecipientName(): ?string
    {
        return $this->recipient_name;
    }

    public function setRecipientName(?string $recipient_name): self
    {
        $this->recipient_name = $recipient_name;

        return $this;
    }

    public function getRecipientZip(): ?int
    {
        return $this->recipient_zip;
    }

    public function setRecipientZip(?int $recipient_zip): self
    {
        $this->recipient_zip = $recipient_zip;

        return $this;
    }

    public function getRecipientCity(): ?string
    {
        return $this->recipient_city;
    }

    public function setRecipientCity(?string $recipient_city): self
    {
        $this->recipient_city = $recipient_city;

        return $this;
    }

    public function getRecipientStreet(): ?string
    {
        return $this->recipient_street;
    }

    public function setRecipientStreet(string $recipient_street): self
    {
        $this->recipient_street = $recipient_street;

        return $this;
    }

    public function getRecipientStreetNumber(): ?int
    {
        return $this->recipient_streetNumber;
    }

    public function setRecipientStreetNumber(?int $recipient_streetNumber): self
    {
        $this->recipient_streetNumber = $recipient_streetNumber;

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getCreationDatetime(): ?\DateTimeInterface
    {
        return $this->creation_datetime;
    }

    public function setCreationDatetime(\DateTimeInterface $creation_datetime): self
    {
        $this->creation_datetime = $creation_datetime;

        return $this;
    }

    /**
     * @return Collection|DHLLabel[]
     */
    public function getDHLLabels(): Collection
    {
        return $this->dHLLabels;
    }

    public function addDHLLabel(DHLLabel $dHLLabel): self
    {
        if (!$this->dHLLabels->contains($dHLLabel)) {
            $this->dHLLabels[] = $dHLLabel;
            $dHLLabel->setProductOrder($this);
        }

        return $this;
    }

    public function removeDHLLabel(DHLLabel $dHLLabel): self
    {
        if ($this->dHLLabels->removeElement($dHLLabel)) {
            // set the owning side to null (unless already changed)
            if ($dHLLabel->getProductOrder() === $this) {
                $dHLLabel->setProductOrder(null);
            }
        }

        return $this;
    }

    public function getVintedItemId(): ?string
    {
        return $this->vinted_item_id;
    }

    public function setVintedItemId(string $vinted_item_id): self
    {
        $this->vinted_item_id = $vinted_item_id;

        return $this;
    }

    public function getPayment(): ?Payment
    {
        return $this->payment;
    }

    public function setPayment(?Payment $payment): self
    {
        $this->payment = $payment;

        return $this;
    }

    public function getPortoPrice(): ?string
    {
        return $this->porto_price;
    }

    public function setPortoPrice(?string $porto_price): self
    {
        $this->porto_price = $porto_price;

        return $this;
    }

    public function getDhlpakid(): ?string
    {
        return $this->dhlpakid;
    }

    public function setDhlpakid(?string $dhlpakid): self
    {
        $this->dhlpakid = $dhlpakid;

        return $this;
    }

    public function getCustomerToken(): ?string
    {
        return $this->customerToken;
    }

    public function setCustomerToken(string $customerToken): self
    {
        $this->customerToken = $customerToken;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="creator")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=Payment::class, mappedBy="user")
     */
    private $payments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $paypalme_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $paypal_clientid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;

    /**
     * @ORM\Column(type="integer")
     */
    private $streetnumber;

    /**
     * @ORM\Column(type="integer")
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $APIToken;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->payments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setCreator($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getCreator() === $this) {
                $order->setCreator(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Payment[]
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(Payment $payment): self
    {
        if (!$this->payments->contains($payment)) {
            $this->payments[] = $payment;
            $payment->setUser($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): self
    {
        if ($this->payments->removeElement($payment)) {
            // set the owning side to null (unless already changed)
            if ($payment->getUser() === $this) {
                $payment->setUser(null);
            }
        }

        return $this;
    }

    public function totalPayments(): float{
        $sum = 0.0;
        foreach ($this->getPayments() as $payment){
            $sum = $sum + $payment->getAmount();
        }
        return $sum;
    }

    public function pendingPayments(): int{
        $count = 0;
        foreach ($this->getPayments() as $payment){
            if($payment->getFulfillmentDate() == null){
                $count++;
            }
        }
        return $count;
    }

    public function pendingPostage(): int{
        $count = 0;
        foreach ($this->getOrders() as $order){
            if(sizeof($order->getDHLLabels()) == 0){
                $count++;
            }
        }
        return $count;
    }

    public function getPaypalmeName(): ?string
    {
        return $this->paypalme_name;
    }

    public function setPaypalmeName(?string $paypalme_name): self
    {
        $this->paypalme_name = $paypalme_name;

        return $this;
    }

    public function getPaypalClientid(): ?string
    {
        return $this->paypal_clientid;
    }

    public function setPaypalClientid(?string $paypal_clientid): self
    {
        $this->paypal_clientid = $paypal_clientid;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getStreetnumber(): ?int
    {
        return $this->streetnumber;
    }

    public function setStreetnumber(int $streetnumber): self
    {
        $this->streetnumber = $streetnumber;

        return $this;
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(int $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAPIToken(): ?string
    {
        return $this->APIToken;
    }

    public function setAPIToken(?string $APIToken): self
    {
        $this->APIToken = $APIToken;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Controller/CustomerController.php
<?php


namespace App\Controller;


use App\Entity\Order;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class CustomerController extends AbstractController
{
    /**
     * @Route("/customer/{token}")
     */
    function customer_addressForm($token, \Symfony\Component\HttpFoundation\Request $request){
        $order = $this->getDoctrine()->getRepository(Order::class)->findOneBy(["customerToken" => $token]);
        if($order == null){
            $this->addFlash('error', 'Dieser Link existiert nicht mehr!');
            return $this->redirectToRoute('app_staticpage_index');
        }

        $view = null;

        if($order->getPayment() != null){
            $form = $this->createForm('App\Form\CustomerDetailFormType', $order);
            $form->handleRequest($request);

            if($form->isSubmitted()){
                $em = $this->getDoctrine()->getManager();
                $em->persist($order);
                $em->flush();

                $this->addFlash('checkmark', '');
            }

            $view = $form->createView();
        }

        return $this->render('content/customer/start.html.twig', [
            "title" => $order->getName(),
            "order" => $order,
            "form" => $view
        ]);
    }
}

templates/content/customer/start.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% if order.recipientName %}
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Bestellung erfolgreich!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Die Bestellung wurde erfolgreich durchgeführt und der Verkäufer hat deine Daten erhalten. <strong>Hier kannst du diese weiterhin ändern!</strong>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fertig</button>
                    </div>
                </div>
            </div>
        </div>

        <script>
            $('#exampleModal').modal({show: true})
        </script>
    {% endif %}

    <div class="row">
        <div class="col-md-10 offset-md-1">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h3 class="card-title">
                        {{ order.name|raw }}
                    </h3>
                </div>
                <div class="card-body">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Über den Kauf</h3>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <tr>
                                    <td><strong>Verkäufer:</strong></td>
                                    <td>{{ order.creator.firstname }} {{ order.creator.lastname }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Preis:</strong></td>
                                    <td>{{ order.price|format_currency('EUR', locale='de') }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Versandkosten:</strong></td>
                                    <td>{% if order.portoPrice %}{{ order.portoPrice|format_currency('EUR', locale='de') }}{% else %}Mit dem Verkäufer vereinbart - siehe Vinted-Produkt!{% endif %}</td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Schritt 1: Bezahlung{% if order.payment %} | <strong class="text-success">Bezahlt</strong>{% endif %}</h3>
                        </div>
                        <div class="card-body text-center">
                            {% if order.creator.paypalClientid %}
                                {% if order.payment == null %}
                                    <script src="https://www.paypal.com/sdk/js?client-id={{ order.creator.paypalClientid|url_encode }}&enable-funding=venmo&currency=EUR" data-sdk-integration-source="button-factory"></script>
                                    <div id="smart-button-container">
                                        <div style="text-align: center;">
                                            <div id="paypal-button-container"></div>
                                        </div>
                                    </div>
                                    <script>
                                        function initPayPalButton() {
                                            paypal.Buttons({
                                                style: {
                                                    shape: 'rect',
                                                    color: 'gold',
                                                    layout: 'vertical',
                                                    label: 'paypal',

                                                },

                                                createOrder: function(data, actions) {
                                                    return actions.order.create({
                                                        purchase_units: [
                                                                {
                                                                    "description":"{{ order.name|raw }}",
                                                                    "amount":{
                                                                        "currency_code":"EUR",
                                                                        "value":{% if order.portoPrice == null %}{{ order.price }}{% else %}+{{ order.portoPrice + order.price }},
                                                                        "breakdown":{
                                                                            "item_total":{
                                                                                "currency_code":"EUR",
                                                                                "value":{{ order.price }}
                                                                            },
                                                                            "shipping":{
                                                                                "currency_code":"EUR",
                                                                                "value":{{ order.portoPrice }}
                                                                            },
                                                                            "tax_total":{
                                                                                "currency_code":"EUR",
                                                                                "value":0.00
                                                                            }
                                                                        }{% endif %}
                                                                    }
                                                                }
                                                            ]
                                                    });
                                                },

                                                onApprove: function(data, actions) {
                                                    return actions.order.capture().then(function(orderData) {

                                                        fetch('/orders/{{ order.id }}/payPalPaid/' + orderData.status);

                                                        // Show a success message within this page, e.g.
                                                        const element = document.getElementById('paypal-button-container');
                                                        element.innerHTML = '';
                                                        element.innerHTML = '<div class="alert alert-success">Die Zahlung ist erfolgt - Der Verkäufer erhält eine eMail, um den Zahlungseingang zu bestätigen!</div><br><br><button class="btn btn-success btn-lg" onclick="window.location.reload()">Weiter zur Adresseingabe</button>';

                                                        // Or go to another URL:  actions.redirect('thank_you.html');

                                                    });
                                                },

                                                onError: function(err) {
                                                    console.log(err);
                                                }
                                            }).render('#paypal-button-container');
                                        }
                                        initPayPalButton();
                                    </script>
                                    {% endif %}
                            {% else %}
                                <div class="alert alert-danger">Der Verkäufer hat keine Zahlungsdaten angegeben! Bitte kontaktiere ihn bezüglich der Bezahlung.<br><strong>Gib daher unten deine Kontaktdaten an!</strong></div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Schritt 2: Adressdaten für den Versand{% if order.recipientName %} | <strong class="text-success">Vollständig</strong>{% endif %}</h3>
                        </div>
                        {% if form %}
                        {{ form_start(form) }}
                        <div class="card-body">
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label class="bmd-label-floating">Name <span class="text-danger">*</span></label>
                                    {{ form_widget(form.recipient_name, {attr: {class: 'form-control'}, required: true}) }}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <label class="bmd-label-floating">Postleitzahl <span class="text-danger">*</span></label>
                                    {{ form_widget(form.recipient_zip, {attr: {class: 'form-control'}, required: true}) }}
                                </div>
                                <div class="form-group col-md-10">
                                    <label class="bmd-label-floating">Ort <span class="text-danger">*</span></label>
                                    {{ form_widget(form.recipient_city, {attr: {class: 'form-control'}, required: true}) }}
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label class="bmd-label-floating">Straße <span class="text-danger">*</span></label>
                                    {{ form_widget(form.recipient_street, {attr: {class: 'form-control'}, required: true}) }}
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="bmd-label-floating">Hausnummer <span class="text-danger">*</span></label>
                                    {{ form_widget(form.recipient_streetNumber, {attr: {class: 'form-control'}, required: true}) }}
                                </div>
                            </div>
                        </div>
                        <div class="card-footer border-top">
                            <button type="submit" class="btn btn-success btn-block">Fertig</button>
                        </div>
                        {{ form_end(form) }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}